---
apiVersion: v1
kind: Pod
metadata:
    name: maven-app-pod
    labels: 
        app: maven-web-app
    namespace: vaibhav-k8s
spec:
    containers:
    - name: maven-app-container
      image: vaibhavjdev/maven-web-app
      ports: 
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: maven-app-svc
  namespace: vaibhav-k8s
spec:
  type: NodePort
#  type: ClusterIP
  selector:
    app: maven-web-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005
...