---
apiVersion: v1
kind: Service
metadata:
  name: maven-app-svc
spec:
  type: NodePort
#  type: ClusterIP
  selector:
    app: maven-web-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005
...