---
apiVersion: v1
kind: Pod
metadata:
    name: maven-app-pod
    labels: 
        app: maven-web-app
spec:
    containers:
    - name: maven-app-container
      image: vaibhavjdev/maven-web-app
      ports: 
        - containerPort: 8080
...
 