---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
spec:
  type: NodePort
  selector:
    app: maven-web-app
    version: v1
  ports:
    - name: app-port-mapping
      protocal: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005
...